#pragma once

#define MAKE_C_VERSION(X,Y) V ## X ## _ ## Y
#define DANGERFARM_CONTACT_VERSION_SYM \
    MAKE_C_VERSION( \
        @DANGERFARM_CONTACT_VERSION_MAJOR@, @DANGERFARM_CONTACT_VERSION_MINOR@)

#define DANGERFARM_CONTACT_VERSION_STRING \
    "@DANGERFARM_CONTACT_VERSION_MAJOR@.@DANGERFARM_CONTACT_VERSION_MINOR@." \
    "@DANGERFARM_CONTACT_VERSION_REL@"
