.PHONY: ALL clean CHECKED_TARGETS RELEASE_TARGETS

COMMON_CFLAGS=$(COMMON_INCLUDES) -Wall -Werror -Wextra -Wpedantic

CHECKED_CC=$(CC)
CHECKED_CFLAGS=$(COMMON_CFLAGS) -fPIC -O0 --coverage

RELEASE_CC=$(CC)
RELEASE_CFLAGS=$(COMMON_CFLAGS) -fPIC -O2

BUILD_DIR=$(CURDIR)/build
CHECKED_BUILD_DIR=$(BUILD_DIR)/checked
RELEASE_BUILD_DIR=$(BUILD_DIR)/release

LIBCONTACT.CHECKED=$(CHECKED_BUILD_DIR)/libcontact.a
LIBCONTACT.RELEASE=$(RELEASE_BUILD_DIR)/libcontact.a
LIBCONTACT_CHECKED_BUILD_DIR=$(CHECKED_BUILD_DIR)/libcontact
LIBCONTACT_RELEASE_BUILD_DIR=$(RELEASE_BUILD_DIR)/libcontact

SRCDIR=$(CURDIR)/src
LIBCONTACT_SRCDIR=$(SRCDIR)/libcontact
LIBCONTACT_DIRS=$(LIBCONTACT_SRCDIR)
LIBCONTACT_SOURCES=$(foreach d,$(LIBCONTACT_DIRS),$(wildcard $(d)/*.c))
LIBCONTACT_STRIPPED_SOURCES=$(patsubst $(SRCDIR)/%,%,$(LIBCONTACT_SOURCES))
LIBCONTACT_CHECKED_DIRS=$(LIBCONTACT_CHECKED_BUILD_DIR)
LIBCONTACT_CHECKED_OBJECTS= \
    $(patsubst %.c,$(CHECKED_BUILD_DIR)/%.o,\
        $(LIBCONTACT_STRIPPED_SOURCES))
LIBCONTACT_RELEASE_DIRS=$(LIBCONTACT_RELEASE_BUILD_DIR)
LIBCONTACT_RELEASE_OBJECTS= \
    $(patsubst %.c,$(RELEASE_BUILD_DIR)/%.o,\
        $(LIBCONTACT_STRIPPED_SOURCES))

ALL: CHECKED_TARGETS RELEASE_TARGETS

clean:
	rm -rf $(BUILD_DIR)

CHECKED_TARGETS: $(LIBCONTACT_CHECKED_DIRS) $(LIBCONTACT.CHECKED)

RELEASE_TARGETS: $(LIBCONTACT_RELEASE_DIRS) $(LIBCONTACT.RELEASE)

$(CHECKED_BUILD_DIR) $(RELEASE_BUILD_DIR):
	mkdir -p $@

$(LIBCONTACT.CHECKED) : $(LIBCONTACT_CHECKED_OBJECTS)
	$(AR) rcs $@ $(LIBCONTACT_CHECKED_OBJECTS)

$(LIBCONTACT_CHECKED_DIRS): $(CHECKED_BUILD_DIR)
	mkdir -p $@

$(CHECKED_BUILD_DIR)/%.o : $(SRCDIR)/%.c $(INCLUDES)
	$(CHECKED_CC) $(CHECKED_CFLAGS) -c -o $@ $<

$(LIBCONTACT.RELEASE) : $(LIBCONTACT_RELEASE_OBJECTS)
	$(AR) rcs $@ $(LIBCONTACT_RELEASE_OBJECTS)

$(LIBCONTACT_RELEASE_DIRS): $(RELEASE_BUILD_DIR)
	mkdir -p $@

$(RELEASE_BUILD_DIR)/%.o : $(SRCDIR)/%.c $(INCLUDES)
	$(RELEASE_CC) $(RELEASE_CFLAGS) -c -o $@ $<
