#include <dangerfarm_contact/status_codes.h>

int nondet_retval();

int random_status_code()
{
    int retval = nondet_retval();

    switch (retval)
    {
        case STATUS_SUCCESS:
        case ERROR_GENERAL_OUT_OF_MEMORY:
        case ERROR_READ_MULTIBYTE_EOF:
        case ERROR_READ_MULTIBYTE_RAW_CONTINUATION:
        case ERROR_READ_MULTIBYTE_INVALID_CONTINUATION:
        case ERROR_READ_MULTIBYTE_OVERLONG_REPRESENTATION:
        case ERROR_READ_MULTIBYTE_UNEXPECTED_CHARACTER:
        case ERROR_READ_MULTIBYTE_CODEPOINT_OUT_OF_RANGE:
        case ERROR_CONTACT_FORM_WRITE:
        case ERROR_CONTACT_FORM_READ:
        case ERROR_CONTACT_FORM_INVALID:
        case ERROR_SOCKET_WRITE:
        case ERROR_SOCKET_READ:
        case ERROR_DATABASE_PROTOCOL_UNEXPECTED_REQUEST_ID:
        case ERROR_DATABASE_PROTOCOL_INVALID_COUNT:
        case ERROR_DATABASE_SYNC:
        case ERROR_DATABASE_ENV_CREATE:
        case ERROR_DATABASE_SET_MAPSIZE:
        case ERROR_DATABASE_SET_MAXDBS:
        case ERROR_DATABASE_ENV_OPEN:
        case ERROR_DATABASE_TXN_BEGIN:
        case ERROR_DATABASE_DBI_OPEN:
        case ERROR_DATABASE_TXN_COMMIT:
        case ERROR_DATABASE_PUT:
        case ERROR_DATABASE_GET:
        case ERROR_DATABASE_DELETE:
        case ERROR_DATABASE_CURSOR_OPEN:
        case ERROR_DATABASE_CURSOR_GET:
        case ERROR_CONTACTDB_MISSING_PARAMETER:
        case ERROR_CONTACTDB_BAD_PARAMETER:
        case ERROR_CONTACTDB_SOCKET_PATH_TOO_LONG:
        case ERROR_CONTACTDB_SOCKET_FAILURE:
        case ERROR_CONTACTDB_UNLINK_FAILURE:
        case ERROR_CONTACTDB_BIND_FAILURE:
        case ERROR_CONTACTDB_LISTEN_FAILURE:
        case ERROR_CONTACTDB_CHMOD_FAILURE:
        case ERROR_CONTACTDB_INVALID_ROLE:
        case ERROR_CONTACTDB_ACCEPT:
        case ERROR_CONTACTDB_PERMISSION_DENIED:
        case ERROR_CONTACTDB_SIGEMPTYSET_FAILURE:
        case ERROR_CONTACTDB_SIGACTION_FAILURE:
        case ERROR_CONTACTDB_FORK:
        case ERROR_CONTACTDB_FORK_PARENT:
        case ERROR_CONTACTDB_SETSID:
        case ERROR_CONTACTDB_GET_INVALID_SIZE:
        case ERROR_CONTACTDB_FULL:
        case ERROR_CONTACTDB_COUNT_MISMATCH:
        case ERROR_CONTACTDB_DROP_PRIVILEGES:
        case ERROR_CTOOL_BAD_PARAMETER:
        case ERROR_CTOOL_BAD_NUMBER:
        case ERROR_CTOOL_NUMBER_OUT_OF_RANGE:
        case ERROR_CTOOL_INVALID_COMMAND:
        case ERROR_CTOOL_SOCKET_PATH_TOO_LONG:
        case ERROR_CTOOL_SOCKET_FAILURE:
        case ERROR_CTOOL_CONNECT_FAILURE:
        case ERROR_CTOOL_DROP_PRIVILEGES:
        case ERROR_CONTACTFORM_INVALID_DROP_PRIVILEGES_STEP:
        case ERROR_CONTACTFORM_DROP_PRIVILEGES:
        case ERROR_CONTACTFORM_SOCKETPAIR:
        case ERROR_CONTACTFORM_FORK:
        case ERROR_CONTACTFORM_SOCKET:
        case ERROR_CONTACTFORM_CONNECT:
        case ERROR_CONTACTFORM_DBSOCK_CLOSE:
        case ERROR_CONTACTFORM_DBPID_KILL:
        case ERROR_CONTACTFORM_DBPID_WAIT:
        case ERROR_CONTACTFORM_KHTTP_PARSE:
        case ERROR_CONTACTFORM_MISSING_FIELD:
        case ERROR_CONTACTFORM_KHTTP_HEAD:
        case ERROR_CONTACTFORM_KHTTP_BODY:
        case ERROR_CONTACTFORM_KHTTP_PUTS:
            return retval;

        default:
            return ERROR_GENERAL_OUT_OF_MEMORY;
    }
}
